using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace protobuf.ws
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeTickerChannelRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"frequency")]
        public float Frequency
        {
            get { return __pbn__Frequency.GetValueOrDefault(); }
            set { __pbn__Frequency = value; }
        }
        public bool ShouldSerializeFrequency() => __pbn__Frequency != null;
        public void ResetFrequency() => __pbn__Frequency = null;
        private float? __pbn__Frequency;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeOrderBookRawChannelRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"depth")]
        public int Depth
        {
            get { return __pbn__Depth.GetValueOrDefault(); }
            set { __pbn__Depth = value; }
        }
        public bool ShouldSerializeDepth() => __pbn__Depth != null;
        public void ResetDepth() => __pbn__Depth = null;
        private int? __pbn__Depth;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeOrderBookChannelRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"depth")]
        public int Depth
        {
            get { return __pbn__Depth.GetValueOrDefault(); }
            set { __pbn__Depth = value; }
        }
        public bool ShouldSerializeDepth() => __pbn__Depth != null;
        public void ResetDepth() => __pbn__Depth = null;
        private int? __pbn__Depth;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeTradeChannelRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeCandleChannelRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"interval", IsRequired = true)]
        public CandleInterval Interval { get; set; } = CandleInterval.Candle1Minute;

        [global::ProtoBuf.ProtoMember(3, Name = @"depth")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int Depth
        {
            get { return __pbn__Depth ?? 0; }
            set { __pbn__Depth = value; }
        }
        public bool ShouldSerializeDepth() => __pbn__Depth != null;
        public void ResetDepth() => __pbn__Depth = null;
        private int? __pbn__Depth;

        [global::ProtoBuf.ProtoContract()]
        public enum CandleInterval
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CANDLE_1_MINUTE")]
            Candle1Minute = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ChannelType channel_type { get; set; } = ChannelType.Ticker;

        [global::ProtoBuf.ProtoMember(2, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ChannelType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TICKER")]
            Ticker = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ORDER_BOOK_RAW")]
            OrderBookRaw = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ORDER_BOOK")]
            OrderBook = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TRADE")]
            Trade = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"CANDLE")]
            Candle = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestExpired : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"now", IsRequired = true)]
        public long Now { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ttl", IsRequired = true)]
        public int Ttl { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"expire_control", IsRequired = true)]
        public RequestExpired ExpireControl { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"api_key", IsRequired = true)]
        public string ApiKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PutLimitOrderRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"expire_control", IsRequired = true)]
        public RequestExpired ExpireControl { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public OrderType order_type { get; set; } = OrderType.Bid;

        [global::ProtoBuf.ProtoMember(4, Name = @"amount", IsRequired = true)]
        public string Amount { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"price", IsRequired = true)]
        public string Price { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum OrderType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BID")]
            Bid = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ASK")]
            Ask = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelLimitOrderRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"expire_control", IsRequired = true)]
        public RequestExpired ExpireControl { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"id", IsRequired = true)]
        public long Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BalanceRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"expire_control", IsRequired = true)]
        public RequestExpired ExpireControl { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"currency", IsRequired = true)]
        public string Currency { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BalancesRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"expire_control", IsRequired = true)]
        public RequestExpired ExpireControl { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"currency")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Currency
        {
            get { return __pbn__Currency ?? ""; }
            set { __pbn__Currency = value; }
        }
        public bool ShouldSerializeCurrency() => __pbn__Currency != null;
        public void ResetCurrency() => __pbn__Currency = null;
        private string __pbn__Currency;

        [global::ProtoBuf.ProtoMember(3, Name = @"only_not_zero")]
        public bool OnlyNotZero
        {
            get { return __pbn__OnlyNotZero.GetValueOrDefault(); }
            set { __pbn__OnlyNotZero = value; }
        }
        public bool ShouldSerializeOnlyNotZero() => __pbn__OnlyNotZero != null;
        public void ResetOnlyNotZero() => __pbn__OnlyNotZero = null;
        private bool? __pbn__OnlyNotZero;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LastTradesRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"expire_control", IsRequired = true)]
        public RequestExpired ExpireControl { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(Interval.Minute)]
        public Interval interval
        {
            get { return __pbn__interval ?? Interval.Minute; }
            set { __pbn__interval = value; }
        }
        public bool ShouldSerializeinterval() => __pbn__interval != null;
        public void Resetinterval() => __pbn__interval = null;
        private Interval? __pbn__interval;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(TradeType.Sell)]
        public TradeType trade_type
        {
            get { return __pbn__trade_type ?? TradeType.Sell; }
            set { __pbn__trade_type = value; }
        }
        public bool ShouldSerializetrade_type() => __pbn__trade_type != null;
        public void Resettrade_type() => __pbn__trade_type = null;
        private TradeType? __pbn__trade_type;

        [global::ProtoBuf.ProtoContract()]
        public enum TradeType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SELL")]
            Sell = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BUY")]
            Buy = 2,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Interval
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MINUTE")]
            Minute = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"HOUR")]
            Hour = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TradesRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"expire_control", IsRequired = true)]
        public RequestExpired ExpireControl { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"currency_pair")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CurrencyPair
        {
            get { return __pbn__CurrencyPair ?? ""; }
            set { __pbn__CurrencyPair = value; }
        }
        public bool ShouldSerializeCurrencyPair() => __pbn__CurrencyPair != null;
        public void ResetCurrencyPair() => __pbn__CurrencyPair = null;
        private string __pbn__CurrencyPair;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(Direction.Asc)]
        public Direction direction
        {
            get { return __pbn__direction ?? Direction.Asc; }
            set { __pbn__direction = value; }
        }
        public bool ShouldSerializedirection() => __pbn__direction != null;
        public void Resetdirection() => __pbn__direction = null;
        private Direction? __pbn__direction;

        [global::ProtoBuf.ProtoMember(4, Name = @"offset")]
        public int Offset
        {
            get { return __pbn__Offset.GetValueOrDefault(); }
            set { __pbn__Offset = value; }
        }
        public bool ShouldSerializeOffset() => __pbn__Offset != null;
        public void ResetOffset() => __pbn__Offset = null;
        private int? __pbn__Offset;

        [global::ProtoBuf.ProtoMember(5, Name = @"limit")]
        public int Limit
        {
            get { return __pbn__Limit.GetValueOrDefault(); }
            set { __pbn__Limit = value; }
        }
        public bool ShouldSerializeLimit() => __pbn__Limit != null;
        public void ResetLimit() => __pbn__Limit = null;
        private int? __pbn__Limit;

        [global::ProtoBuf.ProtoContract()]
        public enum Direction
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ASC")]
            Asc = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"DESC")]
            Desc = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientOrdersRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"expire_control", IsRequired = true)]
        public RequestExpired ExpireControl { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"currency_pair")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CurrencyPair
        {
            get { return __pbn__CurrencyPair ?? ""; }
            set { __pbn__CurrencyPair = value; }
        }
        public bool ShouldSerializeCurrencyPair() => __pbn__CurrencyPair != null;
        public void ResetCurrencyPair() => __pbn__CurrencyPair = null;
        private string __pbn__CurrencyPair;

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        [global::System.ComponentModel.DefaultValue(OrderStatus.Open)]
        public OrderStatus Status
        {
            get { return __pbn__Status ?? OrderStatus.Open; }
            set { __pbn__Status = value; }
        }
        public bool ShouldSerializeStatus() => __pbn__Status != null;
        public void ResetStatus() => __pbn__Status = null;
        private OrderStatus? __pbn__Status;

        [global::ProtoBuf.ProtoMember(4, Name = @"issued_from")]
        public long IssuedFrom
        {
            get { return __pbn__IssuedFrom.GetValueOrDefault(); }
            set { __pbn__IssuedFrom = value; }
        }
        public bool ShouldSerializeIssuedFrom() => __pbn__IssuedFrom != null;
        public void ResetIssuedFrom() => __pbn__IssuedFrom = null;
        private long? __pbn__IssuedFrom;

        [global::ProtoBuf.ProtoMember(5, Name = @"issued_to")]
        public long IssuedTo
        {
            get { return __pbn__IssuedTo.GetValueOrDefault(); }
            set { __pbn__IssuedTo = value; }
        }
        public bool ShouldSerializeIssuedTo() => __pbn__IssuedTo != null;
        public void ResetIssuedTo() => __pbn__IssuedTo = null;
        private long? __pbn__IssuedTo;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(OrderType.Bid)]
        public OrderType order_type
        {
            get { return __pbn__order_type ?? OrderType.Bid; }
            set { __pbn__order_type = value; }
        }
        public bool ShouldSerializeorder_type() => __pbn__order_type != null;
        public void Resetorder_type() => __pbn__order_type = null;
        private OrderType? __pbn__order_type;

        [global::ProtoBuf.ProtoMember(7, Name = @"start_row")]
        public int StartRow
        {
            get { return __pbn__StartRow.GetValueOrDefault(); }
            set { __pbn__StartRow = value; }
        }
        public bool ShouldSerializeStartRow() => __pbn__StartRow != null;
        public void ResetStartRow() => __pbn__StartRow = null;
        private int? __pbn__StartRow;

        [global::ProtoBuf.ProtoMember(8, Name = @"end_row")]
        public int EndRow
        {
            get { return __pbn__EndRow.GetValueOrDefault(); }
            set { __pbn__EndRow = value; }
        }
        public bool ShouldSerializeEndRow() => __pbn__EndRow != null;
        public void ResetEndRow() => __pbn__EndRow = null;
        private int? __pbn__EndRow;

        [global::ProtoBuf.ProtoContract()]
        public enum OrderStatus
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OPEN")]
            Open = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CLOSED")]
            Closed = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"CANCELLED")]
            Cancelled = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"PARTIALLY")]
            Partially = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"NOT_CANCELLED")]
            NotCancelled = 6,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum OrderType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BID")]
            Bid = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ASK")]
            Ask = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TickerEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp", IsRequired = true)]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Last
        {
            get { return __pbn__Last ?? ""; }
            set { __pbn__Last = value; }
        }
        public bool ShouldSerializeLast() => __pbn__Last != null;
        public void ResetLast() => __pbn__Last = null;
        private string __pbn__Last;

        [global::ProtoBuf.ProtoMember(3, Name = @"high")]
        [global::System.ComponentModel.DefaultValue("")]
        public string High
        {
            get { return __pbn__High ?? ""; }
            set { __pbn__High = value; }
        }
        public bool ShouldSerializeHigh() => __pbn__High != null;
        public void ResetHigh() => __pbn__High = null;
        private string __pbn__High;

        [global::ProtoBuf.ProtoMember(4, Name = @"low")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Low
        {
            get { return __pbn__Low ?? ""; }
            set { __pbn__Low = value; }
        }
        public bool ShouldSerializeLow() => __pbn__Low != null;
        public void ResetLow() => __pbn__Low = null;
        private string __pbn__Low;

        [global::ProtoBuf.ProtoMember(5, Name = @"volume")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Volume
        {
            get { return __pbn__Volume ?? ""; }
            set { __pbn__Volume = value; }
        }
        public bool ShouldSerializeVolume() => __pbn__Volume != null;
        public void ResetVolume() => __pbn__Volume = null;
        private string __pbn__Volume;

        [global::ProtoBuf.ProtoMember(6, Name = @"vwap")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Vwap
        {
            get { return __pbn__Vwap ?? ""; }
            set { __pbn__Vwap = value; }
        }
        public bool ShouldSerializeVwap() => __pbn__Vwap != null;
        public void ResetVwap() => __pbn__Vwap = null;
        private string __pbn__Vwap;

        [global::ProtoBuf.ProtoMember(7, Name = @"max_bid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MaxBid
        {
            get { return __pbn__MaxBid ?? ""; }
            set { __pbn__MaxBid = value; }
        }
        public bool ShouldSerializeMaxBid() => __pbn__MaxBid != null;
        public void ResetMaxBid() => __pbn__MaxBid = null;
        private string __pbn__MaxBid;

        [global::ProtoBuf.ProtoMember(8, Name = @"min_ask")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MinAsk
        {
            get { return __pbn__MinAsk ?? ""; }
            set { __pbn__MinAsk = value; }
        }
        public bool ShouldSerializeMinAsk() => __pbn__MinAsk != null;
        public void ResetMinAsk() => __pbn__MinAsk = null;
        private string __pbn__MinAsk;

        [global::ProtoBuf.ProtoMember(9, Name = @"best_bid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BestBid
        {
            get { return __pbn__BestBid ?? ""; }
            set { __pbn__BestBid = value; }
        }
        public bool ShouldSerializeBestBid() => __pbn__BestBid != null;
        public void ResetBestBid() => __pbn__BestBid = null;
        private string __pbn__BestBid;

        [global::ProtoBuf.ProtoMember(10, Name = @"best_ask")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BestAsk
        {
            get { return __pbn__BestAsk ?? ""; }
            set { __pbn__BestAsk = value; }
        }
        public bool ShouldSerializeBestAsk() => __pbn__BestAsk != null;
        public void ResetBestAsk() => __pbn__BestAsk = null;
        private string __pbn__BestAsk;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TickerChannelSubscribedResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<TickerEvent> Datas { get; } = new global::System.Collections.Generic.List<TickerEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderBookRawEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public OrderType order_type { get; set; } = OrderType.Bid;

        [global::ProtoBuf.ProtoMember(2, Name = @"id", IsRequired = true)]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp", IsRequired = true)]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"price")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Price
        {
            get { return __pbn__Price ?? ""; }
            set { __pbn__Price = value; }
        }
        public bool ShouldSerializePrice() => __pbn__Price != null;
        public void ResetPrice() => __pbn__Price = null;
        private string __pbn__Price;

        [global::ProtoBuf.ProtoMember(5, Name = @"quantity", IsRequired = true)]
        public string Quantity { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum OrderType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BID")]
            Bid = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ASK")]
            Ask = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderBookRawChannelSubscribedResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<OrderBookRawEvent> Datas { get; } = new global::System.Collections.Generic.List<OrderBookRawEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderBookEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public OrderType order_type { get; set; } = OrderType.Bid;

        [global::ProtoBuf.ProtoMember(2, Name = @"timestamp", IsRequired = true)]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"price", IsRequired = true)]
        public string Price { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"quantity", IsRequired = true)]
        public string Quantity { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum OrderType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BID")]
            Bid = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ASK")]
            Ask = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderBookChannelSubscribedResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<OrderBookEvent> Datas { get; } = new global::System.Collections.Generic.List<OrderBookEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TradeEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public TradeType trade_type { get; set; } = TradeType.Buy;

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp", IsRequired = true)]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"price", IsRequired = true)]
        public string Price { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"quantity", IsRequired = true)]
        public string Quantity { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum TradeType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BUY")]
            Buy = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SELL")]
            Sell = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TradeChannelSubscribedResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<TradeEvent> Datas { get; } = new global::System.Collections.Generic.List<TradeEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CandleEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp", IsRequired = true)]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"open_price", IsRequired = true)]
        public string OpenPrice { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"close_price", IsRequired = true)]
        public string ClosePrice { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"high_price", IsRequired = true)]
        public string HighPrice { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"low_price", IsRequired = true)]
        public string LowPrice { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"volume", IsRequired = true)]
        public string Volume { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"quoted_volume", IsRequired = true)]
        public string QuotedVolume { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CandleChannelSubscribedResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"interval", IsRequired = true)]
        public SubscribeCandleChannelRequest.CandleInterval Interval { get; set; } = SubscribeCandleChannelRequest.CandleInterval.Candle1Minute;

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        public global::System.Collections.Generic.List<CandleEvent> Datas { get; } = new global::System.Collections.Generic.List<CandleEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelUnsubscribedResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public UnsubscribeRequest.ChannelType Type { get; set; } = UnsubscribeRequest.ChannelType.Ticker;

        [global::ProtoBuf.ProtoMember(2, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ErrorResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code", IsRequired = true)]
        public int Code { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message", IsRequired = true)]
        public string Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TickerNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<TickerEvent> Datas { get; } = new global::System.Collections.Generic.List<TickerEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderBookRawNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<OrderBookRawEvent> Datas { get; } = new global::System.Collections.Generic.List<OrderBookRawEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderBookNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<OrderBookEvent> Datas { get; } = new global::System.Collections.Generic.List<OrderBookEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TradeNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<TradeEvent> Datas { get; } = new global::System.Collections.Generic.List<TradeEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CandleNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"interval", IsRequired = true)]
        public SubscribeCandleChannelRequest.CandleInterval Interval { get; set; } = SubscribeCandleChannelRequest.CandleInterval.Candle1Minute;

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        public global::System.Collections.Generic.List<CandleEvent> Datas { get; } = new global::System.Collections.Generic.List<CandleEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PutLimitOrderResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"order_id", IsRequired = true)]
        public long OrderId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"amount_left", IsRequired = true)]
        public string AmountLeft { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelLimitOrderResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"order_id", IsRequired = true)]
        public long OrderId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"amount_left", IsRequired = true)]
        public string AmountLeft { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BalanceResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public BalanceType Type { get; set; } = BalanceType.Total;

        [global::ProtoBuf.ProtoMember(2, Name = @"currency", IsRequired = true)]
        public string Currency { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"value", IsRequired = true)]
        public string Value { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum BalanceType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TOTAL")]
            Total = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"AVAILABLE")]
            Available = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"AVAILABLE_WITHDRAWAL")]
            AvailableWithdrawal = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TRADE")]
            Trade = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BalancesResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"balances")]
        public global::System.Collections.Generic.List<BalanceResponse> Balances { get; } = new global::System.Collections.Generic.List<BalanceResponse>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LastTradesResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"trades")]
        public global::System.Collections.Generic.List<TradeEvent> Trades { get; } = new global::System.Collections.Generic.List<TradeEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Trade : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"trade_type", IsRequired = true)]
        public TradeEvent.TradeType TradeType { get; set; } = TradeEvent.TradeType.Buy;

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp", IsRequired = true)]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"price", IsRequired = true)]
        public string Price { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"quantity", IsRequired = true)]
        public string Quantity { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"commission", IsRequired = true)]
        public string Commission { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"bonus", IsRequired = true)]
        public string Bonus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TradesResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"trades")]
        public global::System.Collections.Generic.List<Trade> Trades { get; } = new global::System.Collections.Generic.List<Trade>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Order : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"currency_pair", IsRequired = true)]
        public string CurrencyPair { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"good_until_time", IsRequired = true)]
        public long GoodUntilTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public OrderType order_type { get; set; } = OrderType.MarketBuy;

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public OrderStatus order_status { get; set; } = OrderStatus.New;

        [global::ProtoBuf.ProtoMember(6, Name = @"issue_time", IsRequired = true)]
        public long IssueTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"price")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Price
        {
            get { return __pbn__Price ?? ""; }
            set { __pbn__Price = value; }
        }
        public bool ShouldSerializePrice() => __pbn__Price != null;
        public void ResetPrice() => __pbn__Price = null;
        private string __pbn__Price;

        [global::ProtoBuf.ProtoMember(8, Name = @"quantity", IsRequired = true)]
        public string Quantity { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"remaining_quantity", IsRequired = true)]
        public string RemainingQuantity { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"commission_by_trade", IsRequired = true)]
        public string CommissionByTrade { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"bonus_by_trade", IsRequired = true)]
        public string BonusByTrade { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"bonus_rate", IsRequired = true)]
        public string BonusRate { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"commission_rate", IsRequired = true)]
        public string CommissionRate { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"last_modification_time", IsRequired = true)]
        public long LastModificationTime { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum OrderType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MARKET_BUY")]
            MarketBuy = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MARKET_SELL")]
            MarketSell = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"LIMIT_BUY")]
            LimitBuy = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"LIMIT_SELL")]
            LimitSell = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_TYPE")]
            UnknownType = 5,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum OrderStatus
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NEW")]
            New = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"OPEN")]
            Open = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"EXPIRED")]
            Expired = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"CANCELLED")]
            Cancelled = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"EXECUTED")]
            Executed = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"PARTIALLY_FILLED")]
            PartiallyFilled = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"PARTIALLY_FILLED_AND_CANCELLED")]
            PartiallyFilledAndCancelled = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"PARTIALLY_FILLED_AND_EXPIRED")]
            PartiallyFilledAndExpired = 8,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientOrdersResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int totalRows { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int startRow { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int endRow { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"orders")]
        public global::System.Collections.Generic.List<Order> Orders { get; } = new global::System.Collections.Generic.List<Order>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WsRequestMetaData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_type", IsRequired = true)]
        public WsRequestMsgType RequestType { get; set; } = WsRequestMsgType.SubscribeTicker;

        [global::ProtoBuf.ProtoMember(2, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token
        {
            get { return __pbn__Token ?? ""; }
            set { __pbn__Token = value; }
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private string __pbn__Token;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string deprecatedSign
        {
            get { return __pbn__deprecatedSign ?? ""; }
            set { __pbn__deprecatedSign = value; }
        }
        public bool ShouldSerializedeprecatedSign() => __pbn__deprecatedSign != null;
        public void ResetdeprecatedSign() => __pbn__deprecatedSign = null;
        private string __pbn__deprecatedSign;

        [global::ProtoBuf.ProtoMember(4, Name = @"sign")]
        public byte[] Sign
        {
            get { return __pbn__Sign; }
            set { __pbn__Sign = value; }
        }
        public bool ShouldSerializeSign() => __pbn__Sign != null;
        public void ResetSign() => __pbn__Sign = null;
        private byte[] __pbn__Sign;

        [global::ProtoBuf.ProtoContract()]
        public enum WsRequestMsgType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIBE_TICKER")]
            SubscribeTicker = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIBE_ORDER_BOOK_RAW")]
            SubscribeOrderBookRaw = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIBE_ORDER_BOOK")]
            SubscribeOrderBook = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIBE_TRADE")]
            SubscribeTrade = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIBE_CANDLE")]
            SubscribeCandle = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"UNSUBSCRIBE")]
            Unsubscribe = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"LOGIN")]
            Login = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"PUT_LIMIT_ORDER")]
            PutLimitOrder = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"CANCEL_LIMIT_ORDER")]
            CancelLimitOrder = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"BALANCE")]
            Balance = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"BALANCES")]
            Balances = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"LAST_TRADES")]
            LastTrades = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"TRADES")]
            Trades = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_ORDERS")]
            ClientOrders = 14,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WsResponseMetaData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"response_type", IsRequired = true)]
        public WsResponseMsgType ResponseType { get; set; } = WsResponseMsgType.TickerChannelSubscribed;

        [global::ProtoBuf.ProtoMember(2, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token
        {
            get { return __pbn__Token ?? ""; }
            set { __pbn__Token = value; }
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private string __pbn__Token;

        [global::ProtoBuf.ProtoContract()]
        public enum WsResponseMsgType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TICKER_CHANNEL_SUBSCRIBED")]
            TickerChannelSubscribed = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ORDER_BOOK_RAW_CHANNEL_SUBSCRIBED")]
            OrderBookRawChannelSubscribed = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ORDER_BOOK_CHANNEL_SUBSCRIBED")]
            OrderBookChannelSubscribed = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TRADE_CHANNEL_SUBSCRIBED")]
            TradeChannelSubscribed = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"CANDLE_CHANNEL_SUBSCRIBED")]
            CandleChannelSubscribed = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_UNSUBSCRIBED")]
            ChannelUnsubscribed = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR")]
            Error = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"TICKER_NOTIFY")]
            TickerNotify = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"ORDER_BOOK_RAW_NOTIFY")]
            OrderBookRawNotify = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"ORDER_BOOK_NOTIFY")]
            OrderBookNotify = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"TRADE_NOTIFY")]
            TradeNotify = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"CANDLE_NOTIFY")]
            CandleNotify = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"LOGIN_RESPONSE")]
            LoginResponse = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"PUT_LIMIT_ORDER_RESPONSE")]
            PutLimitOrderResponse = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"CANCEL_LIMIT_ORDER_RESPONSE")]
            CancelLimitOrderResponse = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"BALANCE_RESPONSE")]
            BalanceResponse = 16,
            [global::ProtoBuf.ProtoEnum(Name = @"BALANCES_RESPONSE")]
            BalancesResponse = 17,
            [global::ProtoBuf.ProtoEnum(Name = @"LAST_TRADES_RESPONSE")]
            LastTradesResponse = 18,
            [global::ProtoBuf.ProtoEnum(Name = @"TRADES_RESPONSE")]
            TradesResponse = 19,
            [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_ORDERS_RESPONSE")]
            ClientOrdersResponse = 20,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"meta", IsRequired = true)]
        public WsRequestMetaData Meta { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"msg", IsRequired = true)]
        public byte[] Msg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"meta", IsRequired = true)]
        public WsResponseMetaData Meta { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"msg", IsRequired = true)]
        public byte[] Msg { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
